workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - google_play # keystore credentials
    scripts:
      - name: Get dependencies
        script: |
          cd .
          flutter pub get
      - name: Build Android Release
        script: |
          cd .
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

  windows-workflow:
    name: Windows Release
    max_build_duration: 120
    instance_type: windows_x86_64
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd .
          flutter pub get
      - name: Build Windows Release
        script: |
          cd .
          flutter build windows --release
    artifacts:
      - build/windows/runner/Release/*.exe
